### ISSUE TITLE
Login Translation bug

### ISSUE THREAD

**Issue by GiantSparta** [Carve/qbittorrent-webui-cjratliff.com#1]
When the theme is installed and you're in the login menu when entering wrong data it will display a different error code then when having the theme uninstalled see screenshot:
QBT_TR(Invalid Username or Password.)QBT_TR[CONTEXT=HttpServer]
<img width="1280" alt="qBittorrent v4 5 0 Web UI en nog 1 andere pagina - JJ - Microsoft​ Edge 16-1-2023 23_50_45" src="https://user-images.githubusercontent.com/45576830/212776980-d36265b8-2b3b-48c6-95bf-72adde1ca7d9.png">

**Comment by Carve** [comment]
Should be fixed in 1.1.0 (clear cache and hard refresh)
