### ISSUE TITLE
'Last Activity' columns all show infinity

### ISSUE THREAD

**Issue by brian9002** [Carve/qbittorrent-webui-cjratliff.com#10]
![334333](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/134178942/2f10f8ea-a070-46b3-b7a5-6811328a660d)

I've tried Shift+F5

**Comment by Carve** [comment]
I cannot replicate this issue

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/662856/e7a18151-a370-42d8-a695-fd17263a38f2)

**Comment by brian9002** [comment]
I fixed the issue by simply moving the column and the dates populated.

**Comment by brian9002** [comment]
Your Last Activity shows infinity signs and numbers where there should be dates and times, so if you move the column it should fix it.
