### ISSUE TITLE
Great theme! Mine won't color the actual torrents though.

### ISSUE THREAD

**Issue by devanteweary** [Carve/qbittorrent-webui-cjratliff.com#12]
Hey, using this on qTorrent v4.5.4 - Unraid Docker if that matters.

Let me just show you what's happening, might be easier.
Otherwise looks great.

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/29805497/7ce63aeb-8322-4c37-b9c8-d61cf05e70d0)

**Comment by Carve** [comment]
Make sure you're clearing your cache after changing theme.

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/662856/3580beb1-2baa-47b5-b80d-997b519ebf61)

**Comment by devanteweary** [comment]
Good call. That was absolutely it.

And for future people, CTRL+F5 doesn't work.
And interestingly, I tried a different browser and the torrent lines were as intended but the tabs for "General, Trackers, Peers, etc." were still white.

Only after I fully cleared cache in my original browser did it work.

Thanks Carve. You're the best!
