### ISSUE TITLE
Right-click context menu not working

### ISSUE THREAD

**Issue by icenine9** [Carve/qbittorrent-webui-cjratliff.com#17]
Current version of this WebUI does not seem to allow the right-click context menu required for moving torrents, etc. Have attempted to clear cache, refresh, to no avail.  Disabling the Alternate WebUI returns this functionality.

**Comment by Carve** [comment]
Actively working on this already, thanks for the issue report.

**Comment by Carve** [comment]
Added: v1.2.4.1 - Fix for context menu on right click

**Comment by fischy667** [comment]
The menu still does not open when multiple torrents are selected.

![grafik](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/30476701/0dcb787f-8236-4cab-ae60-d25608b0b490)

**Comment by Carve** [comment]
> The menu still does not open when multiple torrents are selected.
> 
> ![grafik](https://user-images.githubusercontent.com/30476701/254692958-0dcb787f-8236-4cab-ae60-d25608b0b490.png)

I will take a look at this today, just confirmed on my remote instance

**Comment by Carve** [comment]
@fischy667 v1.2.5 includes the fix for this, as well as future proofs 3 other locations that could potentially cause an "is null" result.

**Comment by Carve** [comment]
@fischy667 v1.2.5 includes the fix for this, as well as future proofs 3 other locations that could potentially cause an "is null" result.
