### ISSUE TITLE
[FR] Add to qBittorrent wiki

### ISSUE THREAD

**Issue by BakasuraRCE** [Carve/qbittorrent-webui-cjratliff.com#2]
Hi there,

First of all, thank you for creating such a great theme. It's just what I was looking for, and I really appreciate how it maintains the "old UI" compared to other themes like VueTorrent or Flood, which makes the learning curve much easier.

I was wondering if you would consider adding your repository to the [official list](https://github.com/qbittorrent/qBittorrent/wiki/List-of-known-alternate-WebUIs) on the wiki. I think others would really benefit from having access to it.

Thank you again for your work on this theme.

Best regards,

**Comment by Carve** [comment]
Yea, I'll open a merge / pull request for the addition, thanks for the suggestion :)
