### ISSUE TITLE
Minor UI Issues

### ISSUE THREAD

**Issue by Absolutely-Free** [Carve/qbittorrent-webui-cjratliff.com#20]
I just upgraded my torrent server from Debian 11 to 12 and needed to find a new qbittorrent-nox theme because my old theme was incompatible with the new version of qbittorrent-nox. I came upon yours and this was easily the best one I found. The color theme and the icons are great. Thank you very much for putting this together and sharing it with us all!

I did come upon 4 small issues and inconsistencies in the UI as I was exploring it and testing it out:

1. When right clicking on a torrent and hovering over the category option, the new and reset options have the QBT_TR text that appears next to them, as seen below. This is the same issue that my old theme had.
![1](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/93813924/efbe06de-b29b-4d3d-a37e-aea860076b8c)

2. The error message that you receive if you enter in an invalid username/password on the login screen also has the same issue.
![4](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/93813924/128036af-d7a9-4a8d-8a8a-1c19a2c77052)

3. The dropdown from the View option along the header has inconsistently colored backgrounds for the icons. This is the only dropdown that has this issue.
![2](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/93813924/6521a901-0db0-4ca3-b6bf-d3cffd0c1dc1)

4. All of the buttons on the options screen don't have the correct font-family property being applied in the CSS. All of the other buttons (such as on the login screen and the upload button on the upload local torrent screen) have a range of fonts in the font-family CSS property, but all of the buttons in the options screen only have a single font which I don't have installed on my system. There are multiple instances of this issue throughout the different tabs on the options screen (the save button on all tabs, the random button under connection, the "edit auto downloading rules" button under RSS, and the register button under Web UI).
![3](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/93813924/d802c073-239f-4901-9328-d6054d72491a)

I am able to reproduce these issues in both Firefox and Brave (both fully up to date). I am using v1.2.5 of the UI that I just cloned from your repository yesterday. The server is a Debian 12 VM with the version of qbittorrent-nox from the official repositories:

qBittorrent 4.5.2
Qt: 	5.15.8
Libtorrent: 	2.0.8.0
Boost: 	1.74.0
OpenSSL: 	3.0.9
zlib: 	1.2.13

**Comment by Carve** [comment]
Confirmed, will fix today.  Was likely due to the updates required to fix a previous issue.

**Comment by Carve** [comment]
You _may_ need to clear your cache for these fixes
