### ISSUE TITLE
Request for Enchantment Ratio Color

### ISSUE THREAD

**Issue by project-blaze** [Carve/qbittorrent-webui-cjratliff.com#24]
hi,

I am kindly requesting an enchantment ratio color update. If you have the time, could you consider adding an enchantment ratio color? Instead of having three colors, I'd like to suggest that you refer to this author's work for your information: https://github.com/gl0ryus/woq. Additionally, please take a moment to review the attached screenshots, following this example:

- Red: < 1
- Yellow: < 2
![ratio_color](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/99856652/b71f41c0-853b-4b21-b23b-0049f76e9272)

**Comment by Carve** [comment]
I'm going to politely decline.  The colors (while awesome for item tiers) are not what I would imagine for a ratio from 0 to 1+

I am however open to debate this if enough people are interested.
