### ISSUE TITLE
Colors are off

### ISSUE THREAD

**Issue by 4rm4g3dd0n** [Carve/qbittorrent-webui-cjratliff.com#26]
Freshly installed qBit v4.5.4 on Windows. Background colors of the torrents section seem to be using the default theme.
![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/22554335/5a65e9f7-bd70-49b0-8603-0e86f6529834)

**Comment by Carve** [comment]
@4rm4g3dd0n Browser? Please clear your cache entirely (or try incognito / private window) and report back.

**Comment by 4rm4g3dd0n** [comment]
Firefox, clearing cache worked, thanks!
