### ISSUE TITLE
Theme not backwards compatible to qBittorrent version 4.4.1

### ISSUE THREAD

**Issue by Moneysac90** [Carve/qbittorrent-webui-cjratliff.com#32]
The theme doesn't work well with older versions of qBittorrent that are often included as default in linux repositories like ubuntu. The following screenshot shows missing areas for the dark theme. 

<img width="559" alt="image" src="https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/20662108/c10aed28-4c43-4d1a-a1fb-dc5126adecb2">

If the theme could also support older versions I would much appreciate it.

**Comment by Carve** [comment]
> The theme doesn't work well with older versions of qBittorrent that are often included as default in linux repositories like ubuntu. The following screenshot shows missing areas for the dark theme.
> <img alt="image" width="559" src="https://user-images.githubusercontent.com/20662108/266271430-c10aed28-4c43-4d1a-a1fb-dc5126adecb2.png">
> 
> If the theme could also support older versions I would much appreciate it.

Clear your browsers cache
