### ISSUE TITLE
Availability shows seeding rate limit value

### ISSUE THREAD

**Issue by Beimeith** [Carve/qbittorrent-webui-cjratliff.com#33]
As in the title, when using the theme, the Availability column always reports 1.01 regardless of the actual value.

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/7285827/d5ed2123-218b-465c-9db9-6fe3f310dea8)

**Comment by Beimeith** [comment]
Was a cache issue. Clearing cache resolved it.

**Comment by Carve** [comment]
![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/662856/733c10d1-ca1c-4ebe-8c77-09238b4c22ad)
Cannot replicate

**Comment by Beimeith** [comment]
Something is definitely off somewhere. Switching to default the value shows correctly. 

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/7285827/f3a9708a-3e3e-421b-b324-4092b6caf4ec)

And it isn't a cache issue this time, I've cleared it each time I've switched themes.

**Comment by Beimeith** [comment]
It looks to be related to the seeding limit value set in options. Whenever I change that value, the Availability value changes.

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/7285827/759283e9-ad29-41b0-a14c-857330fef240)

**Comment by Beimeith** [comment]
Some additional information:

The issue only appears to present itself if the Ratio Limit column is NOT selected/enabled. If it is not enabled, then the Availability column uses the ratio value. If the Ratio Limit column Is selected/enabled, then the Availability column works correctly. You may need to F5/reload the page for the changes to be reflected.

**Comment by Carve** [comment]
> Some additional information:
> 
> The issue only appears to present itself if the Ratio Limit column is NOT selected/enabled. If it is not enabled, then the Availability column uses the ratio value. If the Ratio Limit column Is selected/enabled, then the Availability column works correctly. You may need to F5/reload the page for the changes to be reflected.

Are you on version 1.2.7.2?

**Comment by Beimeith** [comment]
I tested with 1.2.7.2 and by pulling down the current source and the result is the same.

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/7285827/1288a96f-a997-4e29-b28d-174dc2d6d159)

**Comment by Carve** [comment]
> I tested with 1.2.7.2 and by pulling down the current source and the result is the same.
> 
> ![image](https://user-images.githubusercontent.com/7285827/274448267-1288a96f-a997-4e29-b28d-174dc2d6d159.png)

Great examples, hopefully this will help me debug the JavaScript

**Comment by Carve** [comment]
Please test with today's release of 1.2.8 and re-open if needed.
