### ISSUE TITLE
Ratio Color Additions

### ISSUE THREAD

**Issue by xstefanx** [Carve/qbittorrent-webui-cjratliff.com#34]
This isn't a change that is needed in your releases, but I was wanting to customize some ratio colors for myself similar to request #24 and I seem to be missing something and was hoping you might be able to help guide me.

I was thinking there were only two items that would need to be updated, core.css and dynamicTable.js. Here are the changes I had made to them. 

core.css:
```
.highlight-blue {
	color: var(--highlight-color--blue) !important;
}

.highlight-purple {
	color: var(--highlight-color--purple) !important;
}
```

dynamicTable.js:
```
		} else if (string > "0.80" && string <= "4.99") {
                    td.classList.add('highlight-brightgreen');
                } else if (string > "4.99" && string <= "9.99") {
                    td.classList.add('highlight-blue');
                } else if (string > "9.99") {
                    td.classList.add('highlight-purple');
```

These changes didn't seem to have the desired effect however, anything 4.99 or higher ratio is still showing as bright green, even after a cache clear and browser restart. Is there more to changing this that I overlooked?

**Comment by Carve** [comment]
> This isn't a change that is needed in your releases, but I was wanting to customize some ratio colors for myself similar to request #24 and I seem to be missing something and was hoping you might be able to help guide me.
> 
> I was thinking there were only two items that would need to be updated, core.css and dynamicTable.js. Here are the changes I had made to them.
> 
> core.css:
> 
> ```
> .highlight-blue {
> 	color: var(--highlight-color--blue) !important;
> }
> 
> .highlight-purple {
> 	color: var(--highlight-color--purple) !important;
> }
> ```
> 
> dynamicTable.js:
> 
> ```
> 		} else if (string > "0.80" && string <= "4.99") {
>                     td.classList.add('highlight-brightgreen');
>                 } else if (string > "4.99" && string <= "9.99") {
>                     td.classList.add('highlight-blue');
>                 } else if (string > "9.99") {
>                     td.classList.add('highlight-purple');
> ```
> 
> These changes didn't seem to have the desired effect however, anything 4.99 or higher ratio is still showing as bright green, even after a cache clear and browser restart. Is there more to changing this that I overlooked?

That should be all it requires, have you made sure to clear your cache / try incognito?
