### ISSUE TITLE
Firefox rendering issues.

### ISSUE THREAD

**Issue by acolpan** [Carve/qbittorrent-webui-cjratliff.com#35]
Firefox not rendering the column headers, columns, and the tabs in black background as expected. Please, see the attached image.

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/4216057/043eb4dc-2486-44d2-842c-eea2e9778210)

**Comment by Carve** [comment]
Clear your cache.

**Comment by acolpan** [comment]
Yes, it works now. Thanks.
