### ISSUE TITLE
Default Torrent Management Mode always manual

### ISSUE THREAD

**Issue by mayoko185** [Carve/qbittorrent-webui-cjratliff.com#36]
Hello, LOVE the theme only issue Im having is the Default Torrent Management Mode is always manual even though in the settings it set to automatic as the default, when I disable the theme it works as expected.

Thanks

**Comment by OHIOXOIHO** [comment]
"qbittorrent-webui-cjratliff.com-stable_2\qbittorrent-webui-cjratliff.com-stable\private\download.html"
Edit lines 32 and 33 from:
```
<option selected value="false">Manual</option>
<option value="true">Automatic</option>
```
to:
``` 
<option value="false">Manual</option>
<option selected value="true">Automatic</option>
```

**Comment by mayoko185** [comment]
> "qbittorrent-webui-cjratliff.com-stable_2\qbittorrent-webui-cjratliff.com-stable\private\download.html" Edit lines 32 and 33 from:
> 
> ```
> <option selected value="false">Manual</option>
> <option value="true">Automatic</option>
> ```
> 
> to:
> 
> ```
> <option value="false">Manual</option>
> <option selected value="true">Automatic</option>
> ```

Hi, I applied your fix and looks like magnet links are now defaulting to automatic correctly but not when adding .torrrent files. Thanks :)
