### ISSUE TITLE
White spaces on qBittorrent v4.5.5 WebUI

### ISSUE THREAD

**Issue by softerist** [Carve/qbittorrent-webui-cjratliff.com#37]
This is a known problem, or it's just me?
<img width="1876" alt="1" src="https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/21055555/9601a6bf-767e-478f-8f76-1882033748b0">
![2](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/21055555/c5bf7a67-c345-42da-b6b4-4b4f8236010f)

**Comment by Carve** [comment]
Clear your browsers cache or try an incognito / private browsing window.

**Comment by softerist** [comment]
> Clear your browsers cache or try an incognito / private browsing window.

Thank you!
It's working fine after browser cleaning.

**Comment by Carve** [comment]
Great, glad I could help.
