### ISSUE TITLE
Selection/hover color could be improved slightly for a more polished feel

### ISSUE THREAD

**Issue by iGerman00** [Carve/qbittorrent-webui-cjratliff.com#38]
Love the theme, was looking for something exactly as low key as this. 

At [lines 24-27 in dynamicTable.css](https://github.com/Carve/qbittorrent-webui-cjratliff.com/blob/stable/private/css/dynamicTable.css#L24-L27), there is styling for the hover and selection of the table items, which looks like this: 
![ishare-1698602617](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/36676880/dbc6f189-d6f1-4d6b-b811-cf72d1404c9a)

In my opinion, there is too much contrast, leaving it looking a bit out of place given that the rest of the theme is in a darker domain. Inexplicably, it uses the text color var for the background, and the background color var for the text color.

I propose changing it to:
```css
.dynamicTable tbody tr:hover {
    background-color: var(--darkmode-background-alt2);
    color: var(--darkmode-text-alt)
}
```
For a much cleaner look, while still definitively appearing as a selection:
![ishare-1698602542](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/36676880/aa0fc26c-46bd-4dcd-bab1-8f4408376fd4)

---

In a similar vein, the progress bar styling seems a little too bright. 
![ishare-1698602888](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/36676880/c244f238-471e-4a58-b2d1-d680ad48527c)  

While the cyan ones are okay, the white ones do stand out a bit and look "unthemed". I haven't played around with fixing that but hopefully you'll consider.

**Comment by Carve** [comment]
Ya I actually intended to do this as well as change the progress bar for 0%, among a few other stylistic updates.

**Comment by Carve** [comment]
Updated (among a few other things) in today's release.
![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/662856/ba76556a-4c16-482b-a394-262bd6d03847)
