### ISSUE TITLE
[BUG] Can't rename torrents

### ISSUE THREAD

**Issue by BakasuraRCE** [Carve/qbittorrent-webui-cjratliff.com#4]
Hi,

Whenever I try to rename a torrent, the pop-up with the interface of the start page loads instead. The same thing happens with the "Set location" and "New category" options.

![image](https://user-images.githubusercontent.com/26231582/224846671-0e266238-8cb4-4519-9111-8d2d2ad76113.png)

I think this issue is widespread with pop-ups related to torrent properties. Additionally, I am seeing the same error when uploading a torrent from a file or magnet link.

Best regards.

**Comment by Carve** [comment]
I'm not able to replicate this issue.

What's your browser? OS?

**Comment by BakasuraRCE** [comment]
Firefox and running under https://hub.docker.com/r/linuxserver/qbittorrent latest version

**Comment by BakasuraRCE** [comment]
I think it was related to the cookies. I deleted all of them and restarted the container, and the problem seems to have disappeared. However, now all the pop-ups I mentioned appear with a white background.

![image](https://user-images.githubusercontent.com/26231582/224861847-acf5e9d5-ac05-43f2-8239-cb7c85b984f8.png)

**Comment by Carve** [comment]
Yea, I just ran into this issue myself.  It's due to the iframes having the default white background.  Working on the fix now.

**Comment by BakasuraRCE** [comment]
> Hi,
> 
> Whenever I try to rename a torrent, the pop-up with the interface of the start page loads instead. The same thing happens with the "Set location" and "New category" options.
> 
> ![image](https://user-images.githubusercontent.com/26231582/224846671-0e266238-8cb4-4519-9111-8d2d2ad76113.png)
> 
> I think this issue is widespread with pop-ups related to torrent properties. Additionally, I am seeing the same error when uploading a torrent from a file or magnet link.
> 
> Best regards.

Just for future readers: if you experience the same problem where pop-ups are not visible, it's possible that you installed a previous theme that also installed a "service worker" in your browser. You'll need to unregister it to get everything back to normal.

**Comment by Carve** [comment]
See release 1.2.0 for fixes - Thanks!
