### ISSUE TITLE
In qBittorrent v4.6.0 and above, the webUI has some changed and it is not visible with this dark theme

### ISSUE THREAD

**Issue by lilws** [Carve/qbittorrent-webui-cjratliff.com#41]
I found that there is a some missing in UI:
1. Now Options has a tab call Behavior - use to create log file.
![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/12478478/91420e5b-dcd9-412b-ae51-f39d3daca7f8)

2. In RSS Downloader, there is a new option call Add Tags just under the Assign Category.
![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/12478478/f3b0ba41-89a9-40e9-bf96-5cc4b0c002d4)

**Comment by LsHallo** [comment]
Also setting share ratio is broken. Getting bad request. They added a new option there as well.
![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/22171518/ce489f72-6a2e-4230-84ca-a5fa852d8bcf)
![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/22171518/153073fa-79ee-4776-b356-ee4f46c0620c)

**Comment by hajosattila** [comment]
Firefox

![scrn-2023-12-25-14-46-42](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/1567493/7b44b546-1e25-4032-97f7-1b6291c30ceb)
![scrn-2023-12-25-14-47-17](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/1567493/9c6fd41b-7e31-4ee6-9cf1-f00d95d7c444)

**Comment by tothf** [comment]
Also "Last Activity" field stopped working. Shows an '∞' instead of time passed since last activity.

<img width="405" alt="Screenshot 2023-12-29 at 09 44 45" src="https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/6927606/34e5a5e4-26e4-4059-9f43-b301dedca921">

**Comment by liokii** [comment]
> Firefox
> 
> ![scrn-2023-12-25-14-46-42](https://private-user-images.githubusercontent.com/1567493/292760814-7b44b546-1e25-4032-97f7-1b6291c30ceb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDExOTMsIm5iZiI6MTcwNDY0MDg5MywicGF0aCI6Ii8xNTY3NDkzLzI5Mjc2MDgxNC03YjQ0YjU0Ni0xZTI1LTQwMzItOTdmNy0xYjYyOTFjMzBjZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMTUyMTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQxNzMwOGU1ODM4ZTU4NTY2NDJlMWI0MjUyZTM3OWJiYzJkOTcxOGE1YThiMTE2MzRhNTNkNjlmZDNlNjFjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wQ0-FVtLxkpT4eP3SGlgzxS9MvhSW786OBf-vEyrC3w) ![scrn-2023-12-25-14-47-17](https://private-user-images.githubusercontent.com/1567493/292760815-9c6fd41b-7e31-4ee6-9cf1-f00d95d7c444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDExOTMsIm5iZiI6MTcwNDY0MDg5MywicGF0aCI6Ii8xNTY3NDkzLzI5Mjc2MDgxNS05YzZmZDQxYi03ZTMxLTRlZTYtOWNmMS1mMDBkOTVkN2M0NDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMTUyMTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDYyMDBjYzllNTg1MzBmMGJiOGMwZmE1YWQ2YjMzMTMyYTFhYTJmMjk1MWI1MTY3MTM3MTgzM2JmMzgyOTE2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ljgmD8kM2yL7fMxdncM87ULfa91yX24PaQ8BP0AiND0)

Clearing the site data fixed this for me

**Comment by LsHallo** [comment]
Can confirm, new version fixed the share ratio issue.
Thanks for your work!
