### ISSUE TITLE
Add noindex by default

### ISSUE THREAD

**Issue by Feriman22** [Carve/qbittorrent-webui-cjratliff.com#42]
Hi,

I would suggest that you add noindex to the index.html file by default, because some people expose the qBittorrent web interface to the internet as publicly available, and it would not be good if a simple Google search would find it.

To do that, simply add `<meta name="robots" content="noindex">` line to the` index.html` file:

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/22872515/b360167c-88b3-42cb-be22-2a3c62af0c04)

I know, it's not a big deal, but maybe this trick will help to avoid hacking some installations.

Thanks!
Feriman

**Comment by Carve** [comment]
Would you like to open a pull request with that change? I'd suggest adding it to both index files (public and private)

**Comment by Feriman22** [comment]
I have never done it before, I hope I did it well.

https://github.com/Carve/qbittorrent-webui-cjratliff.com/pull/43
https://github.com/Carve/qbittorrent-webui-cjratliff.com/pull/44

**Comment by Carve** [comment]
Merged, thank you

**Comment by Feriman22** [comment]
@Carve 
Do not forget to mention this issue in [release note](https://github.com/Carve/qbittorrent-webui-cjratliff.com/releases/tag/v1.2.9). ;)
