### ISSUE TITLE
Torrents and couple of ui parts are white

### ISSUE THREAD

**Issue by Mrsalai** [Carve/qbittorrent-webui-cjratliff.com#47]
Its in the title, i am linking pictures, 4.5.5 version of qbittorrent on   ubuntu server, and latest release of the theme.
![Screenshot 2024-01-08 213029](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/106451720/4e67f8a2-2d88-452e-a254-2a4e88deb136)

**Comment by Carve** [comment]
Clear your cache and hard refresh your webUI. Check the resolved issues this has been brought up.

**Comment by Mrsalai** [comment]
> Clear your cache and hard refresh your webUI. Check the resolved issues this has been brought up.

Hey, what do you mean by hard refresh?
Thanks

**Comment by Carve** [comment]
> > Clear your cache and hard refresh your webUI. Check the resolved issues this has been brought up.
> 
> Hey, what do you mean by hard refresh? Thanks

https://filecamp.com/support/problem-solving/hard-refresh/

**Comment by Brodieman** [comment]
Doing a shift F5 to refresh without cookies worked. Thanks!

**Comment by VasilisThePikachu** [comment]
Just as a note on firefox you may have to fully clear your cache too.
