### ISSUE TITLE
Several bars are white not dark as shown in the screenshot

### ISSUE THREAD

**Issue by Brodieman** [Carve/qbittorrent-webui-cjratliff.com#48]
![Screenshot 2024-01-09 115724](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/13592675/f381607f-fac4-4561-90f3-6b75f8d84c62)

**Comment by Carve** [comment]
https://github.com/Carve/qbittorrent-webui-cjratliff.com/issues/47
