### ISSUE TITLE
Ratio Limit column blocks others

### ISSUE THREAD

**Issue by tothf** [Carve/qbittorrent-webui-cjratliff.com#49]
The Ratio Limit field does not have the invisible class by default. This is causing an issue when any other column made visible which is after Ratio Limit because until Ratio Limiy column is hidden any column set to visible, which is after that,  will have the Ratio Limit field value.

<img width="2187" alt="Screenshot 2024-01-11 at 21 29 08" src="https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/6927606/be99040a-218e-4a7f-91c3-738c5bd87470">

Once Ratio Limit column set visible the field after shows the correct value.
<img width="233" alt="Screenshot 2024-01-11 at 21 41 41" src="https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/6927606/d34cc97a-e4fc-4a2f-98d1-13017cb377be">

Workaround is to make Ratio Limit visible, move any column front of Ratio Limit, then hide Ration Limit again.

qBt: 4.6.2

**Comment by Carve** [comment]
@tothf Do you have Ratio disabled in this scenario initially on page load?

**Comment by tothf** [comment]
> @tothf Do you have Ratio disabled in this scenario initially on page load?

Yes, it is disabled by default. The view on the first screenshot is the default column set for a fresh qbittorrent-nox instance.

**Comment by Carve** [comment]
> > @tothf Do you have Ratio disabled in this scenario initially on page load?
> 
> Yes, it is disabled by default. The view on the first screenshot is the default column set for a fresh qbittorrent-nox instance.

Is this still an issue after the last two merges?

**Comment by tothf** [comment]
> > > @tothf Do you have Ratio disabled in this scenario initially on page load?
> > 
> > 
> > Yes, it is disabled by default. The view on the first screenshot is the default column set for a fresh qbittorrent-nox instance.
> 
> Is this still an issue after the last two merges?

Yes. In the meanwhile I've upgraded to qBt 4.6.3 as well.

Ratio Limit column hidden and it is front of Last Activity in order
<img width="1240" alt="Screenshot 2024-01-26 at 13 41 32" src="https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/6927606/a2019331-2d4b-49d8-9237-d40bbf5a6da5">

Once Ratio Limit is made visible and refresh the page
<img width="1340" alt="Screenshot 2024-01-26 at 13 42 04" src="https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/6927606/86b32596-4811-4439-867d-b17b4de2130d">

So it doesn't really matter if you have ratio limit enabled or not the field value will be assigned to whatever field is shown.

The filed order looks like this
<img width="1382" alt="Screenshot 2024-01-26 at 13 44 46" src="https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/6927606/4a93be3b-7c7e-4757-a0b7-872478e38812">

In case you hide both Ratio Limit and Last Activity then make Completed On visible it will have the value from Ratio Limit.
Workaround still works which is enable Ratio Limit and move it behind the field you want to see then hide it again.

**Comment by Carve** [comment]
Fixed by @tothf with #56
