### ISSUE TITLE
Uploading file not possible - Button hidden

### ISSUE THREAD

**Issue by LsHallo** [Carve/qbittorrent-webui-cjratliff.com#50]
When I want to upload a local .torrent file I can't because the button is not visible and only 1x1px. Even that is not clickable.
Worked pre #46 

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/22171518/40a217fb-11e7-4625-835d-6e256abb2078)

**Comment by LsHallo** [comment]
Seems like this change breaks it: https://github.com/Carve/qbittorrent-webui-cjratliff.com/pull/46/files#diff-a67f6fd2da35db10467151d82720ff183eb1ce158788d1864a9ef56e1f924ee2L18

Combined with: https://github.com/Carve/qbittorrent-webui-cjratliff.com/blob/stable/private/css/style.css#L105

**Comment by Carve** [comment]
I'm currently in the hospital with my wife. if you can do a pull request with the fix I'll gladly merge it for you, otherwise it may be the end of the week or the weekend before I get a chance to take a look.

**Comment by LsHallo** [comment]
Fixed in #52

**Comment by Carve** [comment]
> Fixed in #52

Thank you, I've merged it
