### ISSUE TITLE
Not working on qbittorrent-nox. Working on qbittorrent client. [Debian]

### ISSUE THREAD

**Issue by alexnt85** [Carve/qbittorrent-webui-cjratliff.com#54]
I have no problem make it work on the client latest stable version 4.5.2
I can't make it work on nox.
I get: "Unacceptable file type, only regular file is allowed." Then i have to edit WebUI\AlternativeUIEnabled=true to false in the config file to get default webui to work again.
Is there any solution to this?

**Comment by Terrails** [comment]
Unsure if it is maybe your version, but its working fine on v4.6.3 for me.

**Comment by alexnt85** [comment]
> Unsure if it is maybe your version, but its working fine on v4.6.3 for me.

On -nox?

**Comment by Terrails** [comment]
> > Unsure if it is maybe your version, but its working fine on v4.6.3 for me.
> 
> On -nox?

Yes, nox in a docker container on unRAID

**Comment by Carve** [comment]
> I have no problem make it work on the client latest stable version 4.5.2 I can't make it work on nox. I get: "Unacceptable file type, only regular file is allowed." Then i have to edit WebUI\AlternativeUIEnabled=true to false in the config file to get default webui to work again. Is there any solution to this?

Is there a reason you're on 4.5.x?

**Comment by alexnt85** [comment]
> > I have no problem make it work on the client latest stable version 4.5.2 I can't make it work on nox. I get: "Unacceptable file type, only regular file is allowed." Then i have to edit WebUI\AlternativeUIEnabled=true to false in the config file to get default webui to work again. Is there any solution to this?
> 
> Is there a reason you're on 4.5.x?

I run -nox-static now and it's ok!
