### ISSUE TITLE
Uncaught TypeError: torrentsTable.getCurrentTorrentHash is not a function

### ISSUE THREAD

**Issue by tesla-srt** [Carve/qbittorrent-webui-cjratliff.com#58]
Content pane seems to be broken.

Is there a typo somewhere?
``
Uncaught TypeError: torrentsTable.getCurrentTorrentHash is not a function
    at loadTorrentFilesData (prop-files.js:346:40)
    at Object.updateData (prop-files.js:385:9)
    at updatePropertiesPanel (client.js?locale=en&v=1wmr2iu:1300:54)
    at Object.onSelectedRowChanged (dynamicTable.js?locale=en&v=1wmr2iu:1552:13)
    at r.extend.$owner (MooTools-Core-1.6.0-compat-compressed.js:5:18121)
    at Object.selectRow (dynamicTable.js?locale=en&v=1wmr2iu:602:18)
    at r.extend.$owner (MooTools-Core-1.6.0-compat-compressed.js:5:18121)
    at HTMLTableRowElement.<anonymous> (dynamicTable.js?locale=en&v=1wmr2iu:767:40)
    at HTMLTableRowElement.a (MooTools-Core-1.6.0-compat-compressed.js:6:28721)
``    
    
![brave_otlOvO7wen](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/71569052/76c6a950-910b-4148-a0d2-a622a3e8261b)

**Comment by Carve** [comment]
I'm having no issues here. What version of Qbittorrent?

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/662856/c561a559-f51b-4d24-8220-ef896dbbc0db)

**Comment by tesla-srt** [comment]
UPDATE UPDATE:
4.3.5 Base theme... OK
4.3.5 Dark theme... NO
4.6.3 Base theme... NO
4.6.3 Dark theme... NO
 
UPDATE: 
Moved to 4.6.3 and it still doesn't work
It seems it may be related to the latest version of qbittorrent-nox.
Base theme has the same results.

Oh well.

I have 4.2.5

![brave_Einx6uELCP](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/71569052/3a6ac31f-1cc3-4eb6-8994-d82c07285cfc)

My original prop-files.js
https://gist.github.com/tesla-srt/e5c0eefaa66cc8b524f7dd21eee1b6ba

**Comment by Carve** [comment]
> UPDATE UPDATE: 4.3.5 Base theme... OK 4.3.5 Dark theme... NO 4.6.3 Base theme... NO 4.6.3 Dark theme... NO
> 
> UPDATE: Moved to 4.6.3 and it still doesn't work It seems it may be related to the latest version of qbittorrent-nox. Base theme has the same results.
> 
> Oh well.
> 
> I have 4.2.5
> 
> ![brave_Einx6uELCP](https://private-user-images.githubusercontent.com/71569052/303205504-3a6ac31f-1cc3-4eb6-8994-d82c07285cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTU3MDAsIm5iZiI6MTcxMDU1NTQwMCwicGF0aCI6Ii83MTU2OTA1Mi8zMDMyMDU1MDQtM2E2YWMzMWYtMWNjMy00ZWI2LTg5OTQtZDgyYzA3Mjg1Y2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDAyMTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZDNiZmUwZWM4ZTA4MGQ4YTI3NmY2ZGYyY2ZlZTQwZmVkYmNiZGU2YWVhMjY2MzZiZTVmZjZkNzkxNGUzMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IjfMDCPMpzXFfc3SCaGOCSYqvEmgEx_vEiQlAPuImaw)
> 
> My original prop-files.js https://gist.github.com/tesla-srt/e5c0eefaa66cc8b524f7dd21eee1b6ba

I'm using the latest qb-nox (as of 3/15/2024) and I'm not seeing that issue with 4.6.3
