### ISSUE TITLE
qbittorent 4.6.3 does not work

### ISSUE THREAD

**Issue by eduarcor** [Carve/qbittorrent-webui-cjratliff.com#64]
qbittorent 4.6.3 does not work at alll

**Comment by Carve** [comment]
Works fine here?

![qb_4 6 3](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/662856/f0cc445b-aad3-450c-a210-c42ca68207da)

**Comment by eduarcor** [comment]
![Screenshot 2024-03-16 at 03 08 22](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/1464379/e8d5b03b-eeb6-4b3c-8362-052cf53a3a1a)
Not here. Without this alternative UI it works like a charm... is just light (not dark), but this alternative UI it just mess up everything...
Maybe you could share your configuration file here?
Cause I don't understand...

**Comment by Carve** [comment]
> ![Screenshot 2024-03-16 at 03 08 22](https://private-user-images.githubusercontent.com/1464379/313366076-e8d5b03b-eeb6-4b3c-8362-052cf53a3a1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTU3NjcsIm5iZiI6MTcxMDU1NTQ2NywicGF0aCI6Ii8xNDY0Mzc5LzMxMzM2NjA3Ni1lOGQ1YjAzYi1lZWI2LTRiM2MtODM2Mi0wNTJjZjUzYTNhMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTZUMDIxNzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODVjMWRkZTM1NjE5MmNmZGMyNDE2YzQxMmIyMzViOTYwNjZiOTNmNWQ5YzdiNjcyNjlkMTAzZWE0YzZjMTA5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6Ckca7IGEF5vWfTkg_QGYunwwZCK7mGv4EfsXRaUgEI) Not here

Looks like you didn't follow the instructions and clear your cache, please clear your cache and try again.

**Comment by eduarcor** [comment]
The cache is cleared.
I know the problem. Are you using chrome? Cause in my pc works perfectly in Firefox and in Safari but not in Chrome.

EDIT: Nevermind, I updated to latest version of Chrome and worked. Thanks

**Comment by Carve** [comment]
> The cache is cleared. I know the problem. Are you using chrome? Cause in mine works perfectly in Firefox and in Safari but not in Chrome.

Here's in Chrome (latest)
![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/662856/6f51aae0-03f9-48e7-ac11-a603f1d4df1f)
