### ISSUE TITLE
Categories are displayed as 0.0, instead of text

### ISSUE THREAD

**Issue by probain** [Carve/qbittorrent-webui-cjratliff.com#65]
The Category doesn't seem to work with your theme. And is displayed as a red 0.0 (see screenshot). When it is supposed to be text entries, naming the different categories. 
![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/165313617/d1d8861a-bf8f-48d7-b13c-e3794962b6e0)

**Comment by Carve** [comment]
It's working fine for me. Any console errors?

![image](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/662856/5ac986d1-6495-4363-87c4-72145f2d2a59)

**Comment by probain** [comment]
Turned out to be a remnat of Vuetorrent messing things up. Clearing Cookies and Cache cleared it up. Sorry for taking your time. But thanks for quick comment

**Comment by probain** [comment]
This was a non-issue. User error

**Comment by Mxlted** [comment]
I'm having this same issue. Never used Vuetorrent and already cleared cookies. This happens to me when ratio is hidden and after a refresh it is still retained over taking whatever category took its place in line.

Using qBittorrent 4.6.4

https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/40963123/1df79440-cb45-4bc9-9959-0cabee3af54a
