### ISSUE TITLE
Ratio overlapping after being hidden

### ISSUE THREAD

**Issue by Mxlted** [Carve/qbittorrent-webui-cjratliff.com#68]
When the ratio section is hidden, the section afterwards is then overlapped by the ratio number and shows 0.0 or whatever ratio the torrent has. Never used Vuetorrent and already cleared cookies. After a refresh, it is still retained over taking whatever category took its place in line.

Using qBittorrent 4.6.4

https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/40963123/2745a05a-6a1b-4cfa-bc7f-badd33450bc6

**Comment by Mxlted** [comment]
soft fix would be to drag "Ratio" to the end before hiding

**Comment by Carve** [comment]
I seem to also have this issue with the base web UI. Can you replicate it with the base theme?

**Comment by Mxlted** [comment]
> I seem to also have this issue with the base web UI. Can you replicate it with the base theme?

For me the base theme is working in hiding the ratio properly. I've unchecked using the alternative UI of course and tried:

- Refreshing
- Clearing cookies
- Restarting client
- Rearranging hiding and unhiding

on the base theme and functions just fine.

**Comment by Carve** [comment]
@Mxlted are you no longer having this bug?

**Comment by Mxlted** [comment]
> @Mxlted are you no longer having this bug?

I just experienced the same bug with another theme: /nightwalker
So it isn't theme specific.
