### ISSUE TITLE
torrent list renders with white background in Firefox 125.0.3

### ISSUE THREAD

**Issue by astridellensdottir** [Carve/qbittorrent-webui-cjratliff.com#69]
![Screenshot (6)](https://github.com/Carve/qbittorrent-webui-cjratliff.com/assets/75395367/c6d27942-ed20-4e76-89cc-0121f979555d)

I love the theme: qbittorrent doesn't flashbang me whenever i switch to the tab, but it renders the torrent list background as white.

I'm using Firefox 125.0.3 on Windows 10 22H, and the UI displays correctly in Chromium-based browsers (I tried Chrome and Edge).

**Comment by Carve** [comment]
Clear your cache and browser data 

To test: use it in a private window

**Comment by mikul9** [comment]
Clearing cache fixed the issue on my browser.

**Comment by Xevion** [comment]
Yeah, this has happened twice now and I forgot how to do it both times. If anyone is curious how to clear cache super fast without deleting site data (I can't only clear cache for the subdomain I operate my WebUI on), here's how:

Inspect Element > Network Tab > Disable cache > Reload

That's it. Sorry for bumping, this is still an issue technically, so I think my post is relevant.

**Comment by Carve** [comment]
> Yeah, this has happened twice now and I forgot how to do it both times. If anyone is curious how to clear cache super fast without deleting site data (I can't only clear cache for the subdomain I operate my WebUI on), here's how:
> 
> Inspect Element > Network Tab > Disable cache > Reload
> 
> That's it. Sorry for bumping, this is still an issue technically, so I think my post is relevant.

This is not an issue, it is however a browser / cache problem.

**Comment by Xevion** [comment]
> This is not an issue, it is however a browser / cache problem.

What's the difference?

**Comment by Carve** [comment]
> > This is not an issue, it is however a browser / cache problem.
> 
> What's the difference?

The difference is the theme doesn't cause the cache issue.

**Comment by Xevion** [comment]
> The difference is the theme doesn't cause the cache issue.

Okay. So? Why'd you reply then? You already closed the issue.
