### ISSUE TITLE
Issues with qBittorrent v5.0.0

### ISSUE THREAD

**Issue by Feriman22** [Carve/qbittorrent-webui-cjratliff.com#71]
Hi!

I have upgraded my qBittorrent to v5.0.0, and noticed that some functions are not working since then:

- Start torrent from top menu, or for right click menu either
- Stop torrent from top menu, or for right click menu either
- Pause torrent from right click menu
- Showing icons for "stoppedUP"

![2024-09-30 06_52_17-qBittorrent v5 0 0 Web UI](https://github.com/user-attachments/assets/9a005a29-7226-4e79-b478-69084a0bdca6)

Could you please check these issues?

Thanks,
Feriman

**Comment by Carve** [comment]
I will take a look and update when I get a minute, dealing with aftermath of a hurricane currently.

**Comment by shomilsaini** [comment]
Same issue here, using binhex/arch-qbittorrentvpn repo and I had to roll back to version- [4.6.7-1-01](https://github.com/binhex/arch-qbittorrentvpn/releases/tag/4.6.7-1-01)

Please look into it.

Thanks


Edit: 😕
> I will take a look and update when I get a minute, dealing with after math of a hurricane currently.

Just saw your message above. Please take care of yourself and others near you. I hope everyone is safe. Sending prayers. 🙏🏻

**Comment by Carve** [comment]
Please let me know if you run into further issues with v1.5.0

**Comment by MossyGreen** [comment]
@Carve 

I am still having issues with the start/stop/remove buttons. Using the right-click menu to perform those actions works. However, using the buttons has no effect.

**Comment by MossyGreen** [comment]
Actually, upon further testing I've noticed that remove does not work for me using the right click menu either.

**Comment by shomilsaini** [comment]
> Actually, upon further testing I've noticed that remove does not work for me using the right click menu either.

Came across this, you might wanna give it a try while this repo is being fixed. It seems like a native dark mode in qbit.
https://www.reddit.com/r/Piracy/comments/1ftrlhg/qbittorrent_now_has_dark_mode/

I will come back to @Carve 's - dark mode because of beautiful implementation, however the native mode might do it for you in the meanwhile.

I am staying on v4.6.7 in the meanwhile.

Thanks for the quick efforts @Carve ! Hope all is well around and at your home.

**Comment by Feriman22** [comment]
I can confirm that the top bar "Start/Stop" buttons are not working.

![2024-10-02 09_14_30-qBittorrent v5 0 0 Web UI](https://github.com/user-attachments/assets/059591f1-bb15-495d-984c-00b33d1ab767)

@Carve, I hope everything is getting fine over there, and thanks for your effort!

**Comment by alexnt85** [comment]
First of all, I hope you and your family are safe.

I applied the latest version on qbt-static-nox 5.0.0 and couldn't load webui with error "Unacceptable file type, only regular file is allowed".

**Update**:
I can load the webui with the latest theme now but as others mentioned above, most attributes on right click are not working.
For example "set location, rename, move to categories, limit share ratio, force recheck & reannounce". I haven't checked the others.
Also, my categories are still there but all of them show "0" items. So I reset categories on all of my torrents list and tried to categorize them again but still shows zero items.
My tags vanished, too.
I cleared cookies in ff but the issues persist.
Reverted to v1.2.9.1 and could categorize again and my tags appeared too, but there are still the issues mentioned above by others.
I'm going to downgrade to 4.6.7 for the time being.

**Comment by alexnt85** [comment]
> Came across this, you might wanna give it a try while this repo is being fixed. It seems like a native dark mode in qbit.
> https://www.reddit.com/r/Piracy/comments/1ftrlhg/qbittorrent_now_has_dark_mode/

Native dark mode has a very vivid difference for alternating row colors that hurts the eyes.
Carve's theme is much easier to look at.

**Comment by Carve** [comment]
Further fixes and modifications for qB 5.0.0 is now active in the 1.5.0-stable branch.

Please let me know if any of you run into any issues (new or existing).

**Comment by shomilsaini** [comment]
> Further fixes and modifications for qB 5.0.0 is now active in the 1.5.0-stable branch.
> 
> Please let me know if any of you run into any issues (new or existing).

Thanks for the efforts @Carve. I just moved to latest version of qbit today and updated your UI files. Only difference I see is in the settings, advanced tab is not available in your UI vs native UI.

Your WebUI
![image](https://github.com/user-attachments/assets/f64e0f2e-a5e1-41c9-b3fe-42d89ae0f63a)

Native WebUI
![image](https://github.com/user-attachments/assets/a4e8a642-323a-40b0-845a-3ff1eda7a261)

Thanks

**Comment by Carve** [comment]
> > Further fixes and modifications for qB 5.0.0 is now active in the 1.5.0-stable branch.
> > Please let me know if any of you run into any issues (new or existing).
> 
> Thanks for the efforts @Carve. I just moved to latest version of qbit today and updated your UI files. Only difference I see is in the settings, advanced tab is not available in your UI vs native UI.
> 
> Your WebUI ![image](https://private-user-images.githubusercontent.com/46788173/380274050-f64e0f2e-a5e1-41c9-b3fe-42d89ae0f63a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Nzk4NDgsIm5iZiI6MTcyOTg3OTU0OCwicGF0aCI6Ii80Njc4ODE3My8zODAyNzQwNTAtZjY0ZTBmMmUtYTVlMS00MWM5LWIzZmUtNDJkODlhZTBmNjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE4MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZmMzZWUyYjc1YjAwMjA4ZTNkZTEyZjkzNzk1ZjkwMjczYmRjOTlmMzY5ZGExZTNiODJmZmRiNTQ3NmIxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-LRrRLVYW7o7q9ngf81-BLQuMWQfFSyU7rCv2Qi7ptE)
> 
> Native WebUI ![image](https://private-user-images.githubusercontent.com/46788173/380274200-a4e8a642-323a-40b0-845a-3ff1eda7a261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Nzk4NDgsIm5iZiI6MTcyOTg3OTU0OCwicGF0aCI6Ii80Njc4ODE3My8zODAyNzQyMDAtYTRlOGE2NDItMzIzYS00MGIwLTg0NWEtM2ZmMWVkYTdhMjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE4MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMTM5ZWRjZTU4NWQ1MGI4N2M3NGU1NGMzNzQ0MTVkM2U0YmVmYzIxN2ZjZmY1NTMxOTAzZjIwYjJiOTE3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tG-pKPuL5fe1ESVzDjQ6iSQ_LmQUaq-GxDpNEOfX6V8)
> 
> Thanks

Widen your window. It's due to the padding changes as far as I can tell nothing I can do.
![image](https://github.com/user-attachments/assets/6a3be3b1-0487-4c7d-9497-29895892e66b)

**Comment by shomilsaini** [comment]
> > > Further fixes and modifications for qB 5.0.0 is now active in the 1.5.0-stable branch.
> > > Please let me know if any of you run into any issues (new or existing).
> > 
> > 
> > Thanks for the efforts @Carve. I just moved to latest version of qbit today and updated your UI files. Only difference I see is in the settings, advanced tab is not available in your UI vs native UI.
> > Your WebUI ![image](https://private-user-images.githubusercontent.com/46788173/380274050-f64e0f2e-a5e1-41c9-b3fe-42d89ae0f63a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Nzk4NDgsIm5iZiI6MTcyOTg3OTU0OCwicGF0aCI6Ii80Njc4ODE3My8zODAyNzQwNTAtZjY0ZTBmMmUtYTVlMS00MWM5LWIzZmUtNDJkODlhZTBmNjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE4MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZmMzZWUyYjc1YjAwMjA4ZTNkZTEyZjkzNzk1ZjkwMjczYmRjOTlmMzY5ZGExZTNiODJmZmRiNTQ3NmIxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-LRrRLVYW7o7q9ngf81-BLQuMWQfFSyU7rCv2Qi7ptE)
> > Native WebUI ![image](https://private-user-images.githubusercontent.com/46788173/380274200-a4e8a642-323a-40b0-845a-3ff1eda7a261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Nzk4NDgsIm5iZiI6MTcyOTg3OTU0OCwicGF0aCI6Ii80Njc4ODE3My8zODAyNzQyMDAtYTRlOGE2NDItMzIzYS00MGIwLTg0NWEtM2ZmMWVkYTdhMjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE4MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMTM5ZWRjZTU4NWQ1MGI4N2M3NGU1NGMzNzQ0MTVkM2U0YmVmYzIxN2ZjZmY1NTMxOTAzZjIwYjJiOTE3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tG-pKPuL5fe1ESVzDjQ6iSQ_LmQUaq-GxDpNEOfX6V8)
> > Thanks
> 
> Widen your window. It's due to the padding changes as far as I can tell nothing I can do. ![image](https://private-user-images.githubusercontent.com/662856/380278500-6a3be3b1-0487-4c7d-9497-29895892e66b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Nzk5MTAsIm5iZiI6MTcyOTg3OTYxMCwicGF0aCI6Ii82NjI4NTYvMzgwMjc4NTAwLTZhM2JlM2IxLTA0ODctNGM3ZC05NDk3LTI5ODk1ODkyZTY2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxODA2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjA2MGU5OTUwZTNkZjJkNmNhMDM5ODJjMWVhNzQ0NmFmYzBlYzMzMjkyOTNmYTJiMDk1YjFhN2JlZWUwZmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8UqzG2V1DiEV27Mbto2c-1mHgvYsxUwIgVy0x8-B0Z8)

Thanks, silly me. 😂
I am glad it was a quick one.

Thanks!
