### ISSUE TITLE
White background

### ISSUE THREAD

**Issue by xAhlen** [Carve/qbittorrent-webui-cjratliff.com#73]
Hi 
I have a problem that my background is white. 

qbit version v4.6.3

![image](https://github.com/user-attachments/assets/5c44234a-2269-4e02-aaf2-c48fc51a5516)

**Comment by alexnt85** [comment]
Clear browser cookie for qbt address.

**Comment by Carve** [comment]
As @alexnt85 mentioned clear your browser cache and hard refresh the page.
