### ISSUE TITLE
Some areas white, even after clearing cache/hard reloading

### ISSUE THREAD

**Issue by jacksoncooper12** [Carve/qbittorrent-webui-cjratliff.com#75]
![Screenshot 2024-10-03 113845](https://github.com/user-attachments/assets/56859308-bede-4bc2-907c-352718f97977)
![Screenshot 2024-10-03 113904](https://github.com/user-attachments/assets/ab1dd1ab-62f3-401a-b973-94a405017b86)

Happy to provide any extra information you need!

**Comment by jacksoncooper12** [comment]
First image is demonstrating clearing cache/hard reload

**Comment by Carve** [comment]
Does this occur with qB 5.0.0+ and the latest theme?

You seem to be using older qBittorrent in your screenshots.

**Comment by jacksoncooper12** [comment]
Just updated to 5.0.0. Same issue unfortunately. Cleared cache/hard refreshed again before taking this screenshot
<img width="857" alt="image" src="https://github.com/user-attachments/assets/81c2ff8b-c073-4663-b38d-fda66c108cb8">

**Comment by Carve** [comment]
You're not using the latest release, you should only be able to start and stop torrents, not pause them. Pause was removed in lieu of stop.

**Comment by jacksoncooper12** [comment]
The tab title is v5.0.0, and when I click "about" under the help tab, it also says 5.0.0. Confused as to what I'm doing wrong.

**Comment by jacksoncooper12** [comment]
I see what you are saying now. Currently with the latest qBittorrent, latest version of this theme (my issue a minute ago), and hard refreshed with cache cleared:
<img width="855" alt="image" src="https://github.com/user-attachments/assets/ae3f879d-df83-4cb5-8556-e3efdcc48940">
As the page is still loading, it has the correct color scheme in the top right, but once the page finishes loading it changes to white.

**Comment by Carve** [comment]
> I see what you are saying now. Currently with the latest qBittorrent, latest version of this theme (my issue a minute ago), and hard refreshed with cache cleared: <img alt="image" width="855" src="https://private-user-images.githubusercontent.com/66802205/373330219-ae3f879d-df83-4cb5-8556-e3efdcc48940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzUzNjAsIm5iZiI6MTcyNzk3NTA2MCwicGF0aCI6Ii82NjgwMjIwNS8zNzMzMzAyMTktYWUzZjg3OWQtZGY4My00Y2I1LTg1NTYtZTNlZmRjYzQ4OTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDE3MDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NDEyZTVjMTIzY2RlNTczODBmNmU2NWI0MTMzOTNmYWUzZjFlZTNjZmI2OGM2YTk4YmI3NzE1OTcwMDQ3ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iTGsnO9wXLDdPnCaUHzWdEuOlkp0Yy8lH5AUqIuaHcI"> As the page is still loading, it has the correct color scheme in the top right, but once the page finishes loading it changes to white.

Can you replicate this in another browser, perhaps in an private / incognito window?

**Comment by Carve** [comment]
Closing due to no answer after 24 hours. Please re-open if it's still being encountered.
