### ISSUE TITLE
Fixes needed for new version 1.5.1

### ISSUE THREAD

**Issue by alexnt85** [Carve/qbittorrent-webui-cjratliff.com#77]
Thank' s for the new release.

I noticed some other issues:

- Odd rows are not highlighted when cursor hovers over them. Even rows are highlighted correctly.
- There is a blue thin stripe for progress on "General" tab instead of the normal progress bar which previous versions had.
- The frame for "Transfer" & "Information" in "General" tab disappeared. Also, there is no frame for all elements in options menus.
- "Remove" does not open the confirmation window. Instead it removes the torrent immediately but the actual file is still in the downloads location.
- "Set location, Rename, Rename Files(not the whole background- only a part of it), Limit Upload Rate, Limit Share Ratio" open a window with white background.
- Content tab is [not shown correctly](https://postimg.cc/1gM89kfL) 
- Every icon has white background in the menu bar.
- The icon of the category, that a torrent belongs to, is white. Seems somehow as a feature but still it is different from the previous versions.

**Comment by Carve** [comment]
I've fixed the rest, now working on:
- Content tab is [not shown correctly](https://postimg.cc/1gM89kfL)
- "Remove" does not open the confirmation window. Instead it removes the torrent immediately but the actual file is still in the downloads location.

**Comment by alexnt85** [comment]
Thank's again! I will try it asap.
