### ISSUE TITLE
Titles being wrong format.

### ISSUE THREAD

**Issue by xAhlen** [Carve/qbittorrent-webui-cjratliff.com#78]
Hi i don't know if this is just my client but the left context menu is all weird. 

![image](https://github.com/user-attachments/assets/69cd6cf6-a609-4c01-9c42-3055d2c38230)

in filters.html it looks like this.

![image](https://github.com/user-attachments/assets/c376ac7c-829b-4848-b629-71ff85349235)

shouldn't it be like this?

![image](https://github.com/user-attachments/assets/99817ca0-6a61-4069-a5fb-cb228a7c3928)

![image](https://github.com/user-attachments/assets/e6b0268a-86ba-456b-a91f-766aa48156d4)

**Comment by Carve** [comment]
What version of my theme are you on?

**Comment by xAhlen** [comment]
1.5.0

**Comment by Carve** [comment]
> 1.5.0

That's the issue, use latest.
