### ISSUE TITLE
Remove lock icon does not show up

### ISSUE THREAD

**Issue by shomilsaini** [Carve/qbittorrent-webui-cjratliff.com#82]
As per the screenshot attached.
The icon doesn't show up.
Tried chrome/chrome-beta/Firefox both incognito and without.
Also, checking the box to remove files did not work, might be a fluke but it happened twice.

![image](https://github.com/user-attachments/assets/a460fd8b-70e4-4e5f-a743-1861a8e0864b)

Thanks!

**Comment by shomilsaini** [comment]
Just tried to delete another torrent with box checked to delete files.
Files were not deleted.

**Comment by shomilsaini** [comment]
Tried another one, still doesn't delete files.
I am not sure if this is UI issue or qBit issue.

Thanks

**Comment by shomilsaini** [comment]
ok, so the delete issue is with qbit.
Solution - https://github.com/binhex/arch-qbittorrentvpn/issues/272#issuecomment-2395262328

https://github.com/binhex/arch-qbittorrentvpn/issues/272

**Comment by shomilsaini** [comment]
@Carve - the icon still doesn't show up though.

**Comment by shomilsaini** [comment]
@Carve - please reopen this issue. The icon is still not showing.

Thanks

**Comment by Carve** [comment]
@shomilsaini can you confirm what version of the theme and qBittorrent you're using?

This is what I'm seeing:
![image](https://github.com/user-attachments/assets/d80d4798-6451-4dfd-9a07-d21099852457)

**Comment by shomilsaini** [comment]
> @shomilsaini can you confirm what version of the theme and qBittorrent you're using?
> 
> This is what I'm seeing: ![image](https://private-user-images.githubusercontent.com/662856/383000682-d80d4798-6451-4dfd-9a07-d21099852457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODIwMjUsIm5iZiI6MTczMDc4MTcyNSwicGF0aCI6Ii82NjI4NTYvMzgzMDAwNjgyLWQ4MGQ0Nzk4LTY0NTEtNGRmZC05YTA3LWQyMTA5OTg1MjQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQwNDQyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGVjMjc2MTI0MTk1ZmM4Nzg2ZjllYjBkYjc0YmM3ZDVmMzBmY2RhNTJlMWI3ZDVmNjg2MDRjZWI3YzYwMzQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Tb6iRNY4SkXkbbjZZdd5K3eSXraEymAcbWPf4TagemY)

I am running latest stack as below.
latest qbittorent version - [v5.0.1](https://github.com/binhex/arch-qbittorrentvpn/releases)
latest theme version - [v2.0.1](https://github.com/Carve/qbittorrent-webui-cjratliff.com/releases/tag/v2.0.1)

Thanks

**Comment by alexnt85** [comment]
> @shomilsaini can you confirm what version of the theme and qBittorrent you're using?
> 
> This is what I'm seeing: ![image](https://private-user-images.githubusercontent.com/662856/383000682-d80d4798-6451-4dfd-9a07-d21099852457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjY2MDYsIm5iZiI6MTczMDkyNjMwNiwicGF0aCI6Ii82NjI4NTYvMzgzMDAwNjgyLWQ4MGQ0Nzk4LTY0NTEtNGRmZC05YTA3LWQyMTA5OTg1MjQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQyMDUxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjQ1NDc0ZjUxODE0ODgxNzE5YTg5YzgyNWRiNjFiYjI0OWY2ODFiZWIxNzc0NjYyZDc2MmUzNmM2NzkxMDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M9UiOiEyGtQPYXZ8bMTBoEKRjOLYRS3_Sb5UbNySd08)

I confirm that I have the same problem with latest [qbittorrent-nox-static](https://github.com/userdocs/qbittorrent-nox-static).

**Comment by Carve** [comment]
> > @shomilsaini can you confirm what version of the theme and qBittorrent you're using?
> > This is what I'm seeing: ![image](https://private-user-images.githubusercontent.com/662856/383000682-d80d4798-6451-4dfd-9a07-d21099852457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjY2MDYsIm5iZiI6MTczMDkyNjMwNiwicGF0aCI6Ii82NjI4NTYvMzgzMDAwNjgyLWQ4MGQ0Nzk4LTY0NTEtNGRmZC05YTA3LWQyMTA5OTg1MjQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQyMDUxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjQ1NDc0ZjUxODE0ODgxNzE5YTg5YzgyNWRiNjFiYjI0OWY2ODFiZWIxNzc0NjYyZDc2MmUzNmM2NzkxMDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M9UiOiEyGtQPYXZ8bMTBoEKRjOLYRS3_Sb5UbNySd08)
> 
> I confirm that I have the same problem with latest [qbittorrent-nox-static](https://github.com/userdocs/qbittorrent-nox-static).

Any console errors for missing media?

**Comment by shomilsaini** [comment]
> > > @shomilsaini can you confirm what version of the theme and qBittorrent you're using?
> > > This is what I'm seeing: ![image](https://private-user-images.githubusercontent.com/662856/383000682-d80d4798-6451-4dfd-9a07-d21099852457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjY2MDYsIm5iZiI6MTczMDkyNjMwNiwicGF0aCI6Ii82NjI4NTYvMzgzMDAwNjgyLWQ4MGQ0Nzk4LTY0NTEtNGRmZC05YTA3LWQyMTA5OTg1MjQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQyMDUxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjQ1NDc0ZjUxODE0ODgxNzE5YTg5YzgyNWRiNjFiYjI0OWY2ODFiZWIxNzc0NjYyZDc2MmUzNmM2NzkxMDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M9UiOiEyGtQPYXZ8bMTBoEKRjOLYRS3_Sb5UbNySd08)
> > 
> > 
> > I confirm that I have the same problem with latest [qbittorrent-nox-static](https://github.com/userdocs/qbittorrent-nox-static).
> 
> Any console errors for missing media?

No console errors for me.

**Comment by alexnt85** [comment]
> > > @shomilsaini can you confirm what version of the theme and qBittorrent you're using?
> > > This is what I'm seeing: ![image](https://private-user-images.githubusercontent.com/662856/383000682-d80d4798-6451-4dfd-9a07-d21099852457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjY2MDYsIm5iZiI6MTczMDkyNjMwNiwicGF0aCI6Ii82NjI4NTYvMzgzMDAwNjgyLWQ4MGQ0Nzk4LTY0NTEtNGRmZC05YTA3LWQyMTA5OTg1MjQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQyMDUxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjQ1NDc0ZjUxODE0ODgxNzE5YTg5YzgyNWRiNjFiYjI0OWY2ODFiZWIxNzc0NjYyZDc2MmUzNmM2NzkxMDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M9UiOiEyGtQPYXZ8bMTBoEKRjOLYRS3_Sb5UbNySd08)
> > 
> > 
> > I confirm that I have the same problem with latest [qbittorrent-nox-static](https://github.com/userdocs/qbittorrent-nox-static).
> 
> Any console errors for missing media?

By console errors, you mean the log section?

**Comment by shomilsaini** [comment]
> > > > @shomilsaini can you confirm what version of the theme and qBittorrent you're using?
> > > > This is what I'm seeing: ![image](https://private-user-images.githubusercontent.com/662856/383000682-d80d4798-6451-4dfd-9a07-d21099852457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjY2MDYsIm5iZiI6MTczMDkyNjMwNiwicGF0aCI6Ii82NjI4NTYvMzgzMDAwNjgyLWQ4MGQ0Nzk4LTY0NTEtNGRmZC05YTA3LWQyMTA5OTg1MjQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQyMDUxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjQ1NDc0ZjUxODE0ODgxNzE5YTg5YzgyNWRiNjFiYjI0OWY2ODFiZWIxNzc0NjYyZDc2MmUzNmM2NzkxMDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M9UiOiEyGtQPYXZ8bMTBoEKRjOLYRS3_Sb5UbNySd08)
> > > 
> > > 
> > > I confirm that I have the same problem with latest [qbittorrent-nox-static](https://github.com/userdocs/qbittorrent-nox-static).
> > 
> > 
> > Any console errors for missing media?
> 
> By console errors, you mean the log section?

This is what he means..... From the dev console in chrome/browser of your choice.
For chrome you can press "Ctrl+Shift+I" OR Press "F12" in windows.

![image](https://github.com/user-attachments/assets/7630e6f7-20db-413f-a1da-dfd86c98cd19)

Thanks!

**Comment by alexnt85** [comment]
> > > > > @shomilsaini can you confirm what version of the theme and qBittorrent you're using?
> > > > > This is what I'm seeing: ![image](https://private-user-images.githubusercontent.com/662856/383000682-d80d4798-6451-4dfd-9a07-d21099852457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjY2MDYsIm5iZiI6MTczMDkyNjMwNiwicGF0aCI6Ii82NjI4NTYvMzgzMDAwNjgyLWQ4MGQ0Nzk4LTY0NTEtNGRmZC05YTA3LWQyMTA5OTg1MjQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQyMDUxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjQ1NDc0ZjUxODE0ODgxNzE5YTg5YzgyNWRiNjFiYjI0OWY2ODFiZWIxNzc0NjYyZDc2MmUzNmM2NzkxMDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M9UiOiEyGtQPYXZ8bMTBoEKRjOLYRS3_Sb5UbNySd08)
> > > > 
> > > > 
> > > > I confirm that I have the same problem with latest [qbittorrent-nox-static](https://github.com/userdocs/qbittorrent-nox-static).
> > > 
> > > 
> > > Any console errors for missing media?
> > 
> > 
> > By console errors, you mean the log section?
> 
> This is what he means..... From the dev console in chrome/browser of your choice. For chrome you can press "Ctrl+Shift+I" OR Press "F12" in windows.
> 
> ![image](https://private-user-images.githubusercontent.com/46788173/384091450-7630e6f7-20db-413f-a1da-dfd86c98cd19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMTUwMjIsIm5iZiI6MTczMTAxNDcyMiwicGF0aCI6Ii80Njc4ODE3My8zODQwOTE0NTAtNzYzMGU2ZjctMjBkYi00MTNmLWExZGEtZGZkODZjOThjZDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDIxMjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYTdjODYzZmNmZDU5NzU4ZTdkNzQzY2ZkMDRhOGY4NTEyZmQ1MGU1NTAwNDYyZjc2ZThhZTlkMDFlZWMzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nAjxnZJS-U6DRjEHBJjec4V5AYrroDy3t3_gnSR2qm0)
> 
> Thanks!

Ah, I see. 

@Carve 
No errors.

**Comment by shomilsaini** [comment]
Thanks @Carve for your efforts. This is now resolved. I updated to v2.0.2 and it works now.

Much Appreciated :)

**Comment by alexnt85** [comment]
> Thanks @Carve for your efforts. This is now resolved. I updated to v2.0.2 and it works now.
> 
> Much Appreciated :)

Lock icon showed up for me too but it doesn't seem to be functional when I press it. How does it work for you?
