### ISSUE TITLE
Issues on version 2.0.1

### ISSUE THREAD

**Issue by alexnt85** [Carve/qbittorrent-webui-cjratliff.com#83]
Some minor issues:

- Start/ stop torrents not working for any tracker on right click in trackers list on the left panel. Also, text is barely visible when hover cursor over any item on the entire left panel.
- Text in lines that refer to torrents actions such as "torrent restored/ torrent stopped/ torrent resumed" in log, is not visible unless cursor hover over these lines.
- Can you please make the highlighted line in torrents list a bit darker, as it was on older versions?

**Comment by alexnt85** [comment]
I also noticed that ratio limit is stuck to the 3rd option even I set to use the global option. I don't know if this is qbit or the theme's issue.

Also, the highlighted line cannot move up/ down with keyboard arrows in torrents list.

**Comment by iamtherobin** [comment]
The log text defiantly not readable anymore.

Also the in highlighted torrents list, the text in the progress column is not highlighting.

**Comment by iamtherobin** [comment]
The spacing on the sidebar column has increased since 1.4.0 quite a bit. I prefer the more compact spacing. Was easier to when it was more compact and it matched the torrent list when it was compact.

**Comment by Carve** [comment]
> The spacing on the sidebar column has increased since 1.4.0 quite a bit. I prefer the more compact spacing. Was easier to when it was more compact and it matched the torrent list when it was compact.

Yes thats due to the changes in the stock qBittorrent styling, I'm working on restoring and overriding the new with the older version, same with colors, logs visibility, etc.

**Comment by alexnt85** [comment]
Thank's for the new version!

Is it possible to make the highlighted line move up/ down with keyboard arrows?(torrent list, log maybe elsewhere I haven't noticed)

Do I need to open a new issue for this one?

**Comment by Carve** [comment]
> Thank's for the new version!
> 
> Is it possible to make the highlighted line move up/ down with keyboard arrows?(torrent list, log maybe elsewhere I haven't noticed)
> 
> Do I need to open a new issue for this one?

You're welcome to open an issue regarding the traversal of actively selected via arrow keys, I cannot promise however it will be created soon (if ever), I'll have to see how much it can affect the webUI performance wise polling for arrow movement (accessibility technically).

**Comment by alexnt85** [comment]
> > Thank's for the new version!
> > Is it possible to make the highlighted line move up/ down with keyboard arrows?(torrent list, log maybe elsewhere I haven't noticed)
> > Do I need to open a new issue for this one?
> 
> You're welcome to open an issue regarding the traversal of actively selected via arrow keys, I cannot promise however it will be created soon (if ever), I'll have to see how much it can affect the webUI performance wise polling for arrow movement (accessibility technically).

Has anything related to this action changed? Because I could perform such actions as I recall.

**Comment by Carve** [comment]
> > > Thank's for the new version!
> > > Is it possible to make the highlighted line move up/ down with keyboard arrows?(torrent list, log maybe elsewhere I haven't noticed)
> > > Do I need to open a new issue for this one?
> > 
> > 
> > You're welcome to open an issue regarding the traversal of actively selected via arrow keys, I cannot promise however it will be created soon (if ever), I'll have to see how much it can affect the webUI performance wise polling for arrow movement (accessibility technically).
> 
> Has anything related to this action changed? Because I could perform such actions as I recall.

None that I've done, the qBittorrent team however may have modified it.

**Comment by alexnt85** [comment]
> > > > Thank's for the new version!
> > > > Is it possible to make the highlighted line move up/ down with keyboard arrows?(torrent list, log maybe elsewhere I haven't noticed)
> > > > Do I need to open a new issue for this one?
> > > 
> > > 
> > > You're welcome to open an issue regarding the traversal of actively selected via arrow keys, I cannot promise however it will be created soon (if ever), I'll have to see how much it can affect the webUI performance wise polling for arrow movement (accessibility technically).
> > 
> > 
> > Has anything related to this action changed? Because I could perform such actions as I recall.
> 
> None that I've done, the qBittorrent team however may have modified it.

I meant if you aware of such modification in v5 of qbt. Do you believe you can add this function in a newer version of the theme, however?

**Comment by Carve** [comment]
> > > > > Thank's for the new version!
> > > > > Is it possible to make the highlighted line move up/ down with keyboard arrows?(torrent list, log maybe elsewhere I haven't noticed)
> > > > > Do I need to open a new issue for this one?
> > > > 
> > > > 
> > > > You're welcome to open an issue regarding the traversal of actively selected via arrow keys, I cannot promise however it will be created soon (if ever), I'll have to see how much it can affect the webUI performance wise polling for arrow movement (accessibility technically).
> > > 
> > > 
> > > Has anything related to this action changed? Because I could perform such actions as I recall.
> > 
> > 
> > None that I've done, the qBittorrent team however may have modified it.
> 
> I meant if you aware of such modification in v5 of qbt. Do you believe you can add this function in a newer version of the theme, however?

I'm not aware of one, no.

I could add the functionality but like I alluded to previously I'll have to see how that could affect the web UI's performance.
