### ISSUE TITLE
Starting and stopping torrents doesn't work (qBittorrent v4.5.2, webUI theme v2.0.1)

### ISSUE THREAD

**Issue by Absolutely-Free** [Carve/qbittorrent-webui-cjratliff.com#85]
The start and stop torrent buttons seem to have completely stopped working in the latest version of the UI theme on qBittorrent v4.5.2. Clicking them seems to do nothing at all. This is both for the start and stop buttons along the top of the screen as well as the ones in right click context menus. Also if you add a torrent and check the start torrent box, the torrent will be stuck in unknown status. The only way to start a torrent in this version is with force start, which can't then be stopped.

This seems to be an issue with the UI theme because if I disable it (tools > options > webUI > uncheck "use alternate webUI") everything works as expected.

**Comment by Carve** [comment]
Yes they are for the new QBit UI, you'll have to revert to older versions for 4.5.x support again.

**Comment by Absolutely-Free** [comment]
Understood. What is the last version with proper support for 4.5.x? Could the readme be updated to denote this?

**Comment by Carve** [comment]
> Understood. What is the last version with proper support for 4.5.x? Could the readme be updated to denote this?

Yes, I've appended it the bottom of the readme.
