### ISSUE TITLE
Unable to disable "Force resume"

### ISSUE THREAD

**Issue by Piddox** [Carve/qbittorrent-webui-cjratliff.com#88]
As described here:
https://github.com/qbittorrent/qBittorrent/issues/21776

It seems to be an issue related to the carve theme.

**Comment by Carve** [comment]
> As described here: [qbittorrent/qBittorrent#21776](https://github.com/qbittorrent/qBittorrent/issues/21776)
> 
> It seems to be an issue related to the carve theme.

This was already resolved, if you still encounter it please update your theme to the latest release.

**Comment by Piddox** [comment]
You are correct, I hadn't updated my carve version for a long time. That fixed it, thanks!
