### ISSUE TITLE
Errored files: no icon (the red exclamation mark is not showed)

### ISSUE THREAD

**Issue by WalzingMatilda** [Carve/qbittorrent-webui-cjratliff.com#9]
The red exclamation mark icon appears in the "STATUS" menu, but it doesn't show up beside an errored file.
No big deal... just reporting.
I'm using firefox.

**Comment by Carve** [comment]
> The red exclamation mark icon appears in the "STATUS" menu, but it doesn't show up beside an errored file. No big deal... just reporting. I'm using firefox.

Got a photo?

**Comment by WalzingMatilda** [comment]
yes, here it is.
![image](https://user-images.githubusercontent.com/129553000/230336351-81aec9b5-a25f-4943-aaed-a01d0856fcf7.png)

sorry, I initially update with an image for some test I'm doing to change a pair of colours.....

**Comment by Carve** [comment]
> yes, here it is. ![image](https://user-images.githubusercontent.com/129553000/230336351-81aec9b5-a25f-4943-aaed-a01d0856fcf7.png)
> 
> sorry, I initially update with an image for some test I'm doing to change a pair of colours.....

Did you forcefully cause the error or was it something that occurred naturally?

**Comment by WalzingMatilda** [comment]
> Did you forcefully cause the error or was it something that occurred naturally?

Hi, there!
Sorry if I'm late...
To show you the problem, I  voluntarily  introduced  the error changing file permission via chmod...

when it happened the first time,  I was moving partially downloaded files from a version to another version of qbit (on another computer).
It seems the error showed up the first time when I put a folder that was only partially downloaded (to be exact the first file in it was completely downloaded, but the other files has not be flagged, so not downloaded) inside the temp dir instead of the completed dir.
So, probably the error showed up because the file  was in the wrong directory. Not anything anyone attempts on a daily basis ...

**Comment by Carve** [comment]
> > Did you forcefully cause the error or was it something that occurred naturally?
> 
> Hi, there! Sorry if I'm late... To show you the problem, I voluntarily introduced the error changing file permission via chmod...
> 
> when it happened the first time, I was moving partially downloaded files from a version to another version of qbit (on another computer). It seems the error showed up the first time when I put a folder that was only partially downloaded (to be exact the first file in it was completely downloaded, but the other files has not be flagged, so not downloaded) inside the temp dir instead of the completed dir. So, probably the error showed up because the file was in the wrong directory. Not anything anyone attempts on a daily basis ...

Ok, the reason I ask is I'm not able to replicate this without forcefully doing something with a file, in which case I believe it fails to do the file check functionality that shows the appropriate icon, however if it were to fail naturally I assume it would work as intended.

**Comment by WalzingMatilda** [comment]
With this new release, the red exclamation mark icon is now showing up when triggered
